const messages = [
    "This is where it all begins...",
    "Commit committed",
    "Version control is awful",
    "COMMIT ALL THE FILES!",
    "The same thing we do every night, Pinky - try to take over the world!",
    "Lock S-foils in attack position",
    "This commit is a lie",
    "I'll explain when you're older!",
    "Here be Dragons",
    "Reinventing the wheel. Again.",
    "This is not the commit message you are looking for",
    "Batman! (this commit has no parents)",
    "Fixed the bug caused by someone else, but it's always my fault",
    "Added a banner that says 'Under construction'",
    "Removed code due to pesky laws of physics",
    "The last time I tried this the monkey didn't survive. Let's hope it works better this time.",
    "I dedicate all this code, all my work, to my wife, Darlene, who will have to support me and our three children and the dog once it gets committed.",
    "It's not a bug – it's an undocumented feature.",
    "It works on my machine.",
    "How did that get in there?",
    "I should get a raise for this.",
    "Finished messing around.",
    "You wouldn't get this from any other guy.",
    "Oops.",
    "That's just how I roll",
    "Reticulating splines...",
    "Moving stuff around",
    "Push poorly written test can down the road another day",
    "Adding additional layer of abstraction",
    "You asked for it!",
    "Committing in accordance with the prophecy.",
    "LOL, fix previous fix",
    "I know what I am doing. Trust me.",
    "To those I leave behind, good luck!",
    "Refactored configuration.",
    "This should work until December 2013.",
    "Does this work?",
    "I'm just a commit and life's a nightmare.",
    "Undoing last commit's mess.",
    "Committing fixes in the dark, seriously, FIX YOUR LIGHTS!",
    "May the Force be with you.",
    "Fixed what was broken.",
    "Breaking stuff...",
    "Implementing AI for automatic bug fixes.",
    "Let's hope it's better now.",
    "I would rather be playing SC2.",
    "lol, typo",
    "Hold my beer, I got this.",
    "Updating the update",
    "Applied fix from the Internet.",
    "Magic, do not touch.",
    "This is why the cat shouldn't sit on my keyboard.",
    "Removed test code that was causing a real bug.",
    "Added some filthy hacks.",
    "Still don't know what I'm doing.",
    "Made it work.",
    "Making this up as I go.",
    "I'm too old for this stuff.",
    "Fixed the fix.",
    "For great justice.",
    "Tuned the algorithm.",
    "Shoveling coal into the server.",
    "Patched another hole.",
    "Squashed some bugs.",
    "Cleared the cobwebs.",
    "Making the world a better place one bug at a time.",
    "Spilled coffee on my keyboard, now it works better.",
    "Commit, then coffee.",
    "Fixed everything.",
    "We'll figure it out on Monday.",
    "That could've been bad...",
    "Hackity Hack!",
    "Reduced code by 42 lines.",
    "One does not simply merge into master",
    "Fingers crossed!",
    "Fixed the broken thing with a thing",
    "I don’t know why. Just move on.",
    "You wouldn't believe it, but I have to tell you...",
    "That's just how I roll",
    "And so the adventure begins.",
    "Keep calm and commit.",
    "Fixed a bug introduced by last bug fix",
    "Divide by zero error fixed.",
    "Someone should really fix this.",
    "TODO: Insert witty commit message",
    "Adding insult to injury.",
    "Committing in accordance with the prophecy.",
    "It's a feature, not a bug.",
    "Don’t tell me you’re too blind to see.",
    "Let's push and leave office.",
    "Removed code due to GDPR.",
    "I am Root. We are Groot.",
    "Another day, another bug.",
    "Out for coffee!",
    "Why is this so hard?",
    "Don’t mess with Voodoo.",
    "Deleted code is debugged code.",
    "This is where it ends...",
    "Obligatory placeholder commit message",
    "Wait, what?",
    "High Hopes - this commit will not disappoint.",
    "Whatever it takes - to get this code working.",
    "Believer - in magic numbers and unicorns.",
    "Victorious - finally, this bug is gone!",
    "Radioactive - this code is glowing with potential.",
    "On Top of the World - that feature worked first try!",
    "Legends - because we're all legends in our git histories.",
    "Natural - writing code like it's second nature.",
    "Born For This - like it was meant to be.",
    "Unstoppable - no bugs can hold us back.",
    "Warriors - ready for any coding challenge.",
    "Revolutionary - changing the codebase, one commit at a time."
  ];
  const colorCodes = [
    "\x1b[31m", 
    "\x1b[32m", 
    "\x1b[33m", 
    "\x1b[34m", 
    "\x1b[35m", 
    "\x1b[36m", 
];
  const funnyCommit = () => {
    const message = messages[Math.floor(Math.random() * messages.length)];
    const colors = colorCodes[Math.floor(Math.random() * colorCodes.length)];
    console.log(`${colors}${message}\x1b[0m`);
  }
  
  module.exports = {
    funnyCommit
  };